---
- name: 'Check variables'
  ansible.builtin.assert:
    that:
      - openvpn_auth in supported_auth
    fail_msg: 'Unsupported configuration!'

- name: 'Install packages'
  ansible.builtin.package:
    name:
      - 'openvpn'
      - 'haveged'
    state: 'present'

- name: 'Ensure services'
  ansible.builtin.service:
    name: "{{ service }}"
    state: 'started'
    enabled: true
  loop:
    - 'haveged'
  loop_control:
    loop_var: 'service'

- name: 'Ensure OpenVPN config directories'
  ansible.builtin.file:
    path: "/etc/openvpn/{{ dir['name'] }}"
    state: 'directory'
    mode: "{{ dir['mode'] }}"
    owner: 'root'
    group: 'root'
  loop:
    - {name: 'bin', mode: '0755'}
    - {name: 'ccd', mode: '0755'}
    - {name: 'private', mode: '0700'}
  loop_control:
    loop_var: 'dir'

- name: 'Ensure OpenVPN log directory'
  ansible.builtin.file:
    path: '/var/log/openvpn'
    state: 'directory'
    mode: '0755'
    owner: 'root'
    group: 'root'

- name: 'Ensure authentication scrip'
  when: openvpn_auth == 'script'
  block:
    - name: 'Ensure OpenVPN authentication script'
      ansible.builtin.copy:
        src: 'authenticate.sh'
        dest: '/etc/openvpn/bin/authenticate.sh'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: 'Ensure password file present'
      ansible.builtin.copy:
        src: 'passwd.example'
        dest: '/etc/openvpn/private/passwd'
        owner: 'root'
        group: 'root'
        mode: '0640'
        force: false

- name: 'Ensure OpenVPN server config'
  ansible.builtin.template:
    src: 'server.conf.j2'
    dest: '/etc/openvpn/server.conf'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: 'Restart openvpn'

- name: 'Ensure kernel system parameters'
  ansible.posix.sysctl:
    name: "{{ sysctl_param.name }}"
    value: "{{ sysctl_param.value }}"
    state: 'present'
    sysctl_set: true
    reload: true
  loop:
    - name: 'net.ipv4.ip_forward'
      value: 1
    - name: 'net.ipv4.ip_no_pmtu_disc'
      value: 1
    - name: 'net.ipv4.conf.all.accept_redirects'
      value: 0
    - name: 'net.ipv4.conf.all.send_redirects'
      value: 0
  loop_control:
    loop_var: 'sysctl_param'

- name: 'Ensure DHparams'
  community.crypto.openssl_dhparam:
    path: '/etc/openvpn/dhparams.pem'
    size: "{{ openvpn_dhparams_size }}"
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Setup firewall'
  ansible.builtin.import_tasks: 'firewall_iptables.yml'
  when:
    - ansible_facts['os_family'] == 'Debian'
    - openvpn_manage_firewall

- name: 'Setup firewall'
  ansible.builtin.import_tasks: 'firewall_firewalld.yml'
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - openvpn_manage_firewall

- name: 'Enable and start service'
  ansible.builtin.service:
    name: 'openvpn@server'
    state: 'started'
    enabled: true
